name: Build ForcePad

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build iOS dylib
        run: |
          SDK="$(xcrun --sdk iphoneos --show-sdk-path)"

          xcrun --sdk iphoneos clang \
          -arch arm64 \
          -miphoneos-version-min=15.0 \
          -isysroot "$(xcrun --sdk iphoneos --show-sdk-path)" \
          -dynamiclib \
          ForcePad.m \
          -install_name @rpath/LOGIC_CRASH_TEST.dylib \
          -o LOGIC_CRASH_TEST.dylib

          file LOGIC_CRASH_TEST.dylib
          xcrun vtool -show-build LOGIC_CRASH_TEST.dylib || true

          - name: Upload ExitTest
          uses: actions/upload-artifact@v4
          with:
            name: LOGIC_CRASH_TEST
            path: LOGIC_CRASH_TEST.dylib
